(ns ^:no-doc zprint.zfns)

;;
;; # Functions for traversal of either zippers or s-expressions
;;
;; Defined by `binding` in either sutil.cljc or zutil.cljc
;;

(def ^:dynamic zstring nil)
(def ^:dynamic znumstr nil)
(def ^:dynamic zbyte-array? nil)
(def ^:dynamic zcomment? nil)
(def ^:dynamic zsexpr nil)
(def ^:dynamic zseqnws nil)
(def ^:dynamic zmap-right nil)
(def ^:dynamic zfocus-style nil)
(def ^:dynamic zfirst nil)
(def ^:dynamic zfirst-no-comment nil)
(def ^:dynamic zsecond nil)
(def ^:dynamic zthird nil)
(def ^:dynamic zfourth nil)
(def ^:dynamic znthnext nil)
(def ^:dynamic zcount nil)
(def ^:dynamic zmap nil)
(def ^:dynamic zmap-w-nl nil)
(def ^:dynamic zanonfn? nil)
(def ^:dynamic zfn-obj? nil)
(def ^:dynamic zfocus nil)
(def ^:dynamic zfind-path nil)
(def ^:dynamic zwhitespace? nil)
(def ^:dynamic zlist? nil)
(def ^:dynamic zvector? nil)
(def ^:dynamic zmap? nil)
(def ^:dynamic zset? nil)
(def ^:dynamic zcoll? nil)
(def ^:dynamic zuneval? nil)
(def ^:dynamic zmeta? nil)
(def ^:dynamic ztag nil)
(def ^:dynamic zlast nil)
(def ^:dynamic zarray? nil)
(def ^:dynamic zatom? nil)
(def ^:dynamic zderef nil)
(def ^:dynamic zrecord? nil)
(def ^:dynamic zns? nil)
(def ^:dynamic zobj-to-vec nil)
(def ^:dynamic zexpandarray nil)
(def ^:dynamic znewline? nil)
(def ^:dynamic zwhitespaceorcomment? nil)
(def ^:dynamic zmap-all nil)
(def ^:dynamic zpromise? nil)
(def ^:dynamic zfuture? nil)
(def ^:dynamic zdelay? nil)
(def ^:dynamic zkeyword? nil)
(def ^:dynamic zconstant? nil)
(def ^:dynamic zagent? nil)
(def ^:dynamic zreader-macro? nil)
(def ^:dynamic zarray-to-shift-seq nil)
(def ^:dynamic zdotdotdot nil)
(def ^:dynamic zsymbol? nil)
(def ^:dynamic znil? nil)
(def ^:dynamic zreader-cond-w-symbol? nil)
(def ^:dynamic zreader-cond-w-coll? nil)
(def ^:dynamic zlift-ns nil)
(def ^:dynamic zinlinecomment? nil)
(def ^:dynamic zfind nil)
(def ^:dynamic ztake-append nil)
